UWUS = [
    "(・`ω´・)",
    ";;w;;",
    "owo",
    "UwU",
    ">w<",
    "^w^",
    r"\(^o\) (/o^)/",
    "( ^ _ ^)∠☆",
    "(ô_ô)",
    "~:o",
    ";-;",
    "(*^*)",
    "(>_",
    "(♥_♥)",
    "*(^O^)*",
    "((+_+))",
]

FACEREACTS = [
    "ʘ‿ʘ",
    "ヾ(-_- )ゞ",
    "(っ˘ڡ˘ς)",
    "(´ж｀ς)",
    "( ಠ ʖ̯ ಠ)",
    "(° ͜ʖ͡°)╭∩╮",
    "(ᵟຶ︵ ᵟຶ)",
    "(งツ)ว",
    "ʚ(•｀",
    "(っ▀¯▀)つ",
    "(◠﹏◠)",
    "( ͡ಠ ʖ̯ ͡ಠ)",
    "( ఠ ͟ʖ ఠ)",
    "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ",
    "(⊃｡•́‿•̀｡)⊃",
    "(._.)",
    "{•̃_•̃}",
    "(ᵔᴥᵔ)",
    "♨_♨",
    "⥀.⥀",
    "ح˚௰˚づ ",
    "(҂◡_◡)",
    "ƪ(ړײ)‎ƪ​​",
    "(っ•́｡•́)♪♬",
    "◖ᵔᴥᵔ◗ ♪ ♫ ",
    "(☞ﾟヮﾟ)☞",
    "[¬º-°]¬",
    "(Ծ‸ Ծ)",
    "(•̀ᴗ•́)و ̑̑",
    "ヾ(´〇`)ﾉ♪♪♪",
    "(ง'̀-'́)ง",
    "ლ(•́•́ლ)",
    "ʕ •́؈•̀ ₎",
    "♪♪ ヽ(ˇ∀ˇ )ゞ",
    "щ（ﾟДﾟщ）",
    "( ˇ෴ˇ )",
    "눈_눈",
    "(๑•́ ₃ •̀๑) ",
    "( ˘ ³˘)♥ ",
    "ԅ(≖‿≖ԅ)",
    "♥‿♥",
    "◔_◔",
    "⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾",
    "乁( ◔ ౪◔)「      ┑(￣Д ￣)┍",
    "( ఠൠఠ )ﾉ",
    "٩(๏_๏)۶",
    "┌(ㆆ㉨ㆆ)ʃ",
    "ఠ_ఠ",
    "(づ｡◕‿‿◕｡)づ",
    "(ノಠ ∩ಠ)ノ彡( \\o°o)\\",
    "“ヽ(´▽｀)ノ”",
    "༼ ༎ຶ ෴ ༎ຶ༽",
    "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
    "(づ￣ ³￣)づ",
    "(⊙.☉)7",
    "ᕕ( ᐛ )ᕗ",
    "t(-_-t)",
    "(ಥ⌣ಥ)",
    "ヽ༼ ಠ益ಠ ༽ﾉ",
    "༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽",
    "ミ●﹏☉ミ",
    "(⊙_◎)",
    "¿ⓧ_ⓧﮌ",
    "ಠ_ಠ",
    "(´･_･`)",
    "ᕦ(ò_óˇ)ᕤ",
    "⊙﹏⊙",
    "(╯°□°）╯︵ ┻━┻",
    r"¯\_(⊙︿⊙)_/¯",
    "٩◔̯◔۶",
    "°‿‿°",
    "ᕙ(⇀‸↼‶)ᕗ",
    "⊂(◉‿◉)つ",
    "V•ᴥ•V",
    "q(❂‿❂)p",
    "ಥ_ಥ",
    "ฅ^•ﻌ•^ฅ",
    "ಥ﹏ಥ",
    "（ ^_^）o自自o（^_^ ）",
    "ಠ‿ಠ",
    "ヽ(´▽`)/",
    "ᵒᴥᵒ#",
    "( ͡° ͜ʖ ͡°)",
    "┬─┬﻿ ノ( ゜-゜ノ)",
    "ヽ(´ー｀)ノ",
    "☜(⌒▽⌒)☞",
    "ε=ε=ε=┌(;*´Д`)ﾉ",
    "(╬ ಠ益ಠ)",
    "┬─┬⃰͡ (ᵔᵕᵔ͜ )",
    "┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻",
    r"¯\_(ツ)_/¯",
    "ʕᵔᴥᵔʔ",
    "(`･ω･´)",
    "ʕ•ᴥ•ʔ",
    "ლ(｀ー´ლ)",
    "ʕʘ̅͜ʘ̅ʔ",
    "（　ﾟДﾟ）",
    r"¯\(°_o)/¯",
    "(｡◕‿◕｡)",
]

RUNSREACTS = [
    "Hey! Nereye gidiyorsun?",
    "Ha? Ne? kaçtılar mı?",
    "ZZzzZZzz... Noldu? oh, yine onlarmış, boşver.",
    "Geri gel!",
    "Kaçın OneBot geliyor !!",
    "Duvara dikkat et!",
    "Beni onlarla sakın yalnız bırakma!!",
    "Kaçarsan, ölürsün.",
    "Şakacı seni, Ben heryerdeyim.",
    "Bunu yaptığına pişman olacaksın...",
    "/kickme tuşunuda deneyebilirsin, Eğlenceli olduğunu söylüyorlar.",
    "Git başka birini rahatsız et, burda kimse takmıyor.",
    "Kaçabilirsin ama saklanamazsın.",
    "Yapabildiklerin bunlar mı?",
    "Arkandayım...",
    "Misafirlerin var!",
    "Bunu kolay yoldan yapabiliriz, yada zor yoldan.",
    "Anlamıyorsun, değil mi?",
    "Haha, kaçsan iyi edersin.!",
    "Lütfen, hatırlat bana ne kadar aldırıyorum?",
    "Senin yerinde olsam daha hızlı kaçardım.",
    "Bu kesinlikle aradığımız robot.",
    "Belki şans sana güler.",
    "Ünlü son sözler.",
    "Ve sonsuza dek yok oldular, hiç görünmediler.",
    "\"Hey, bana bakın! Bottan kaçabiliyorum çok havalıyım!\" - bu kişi",
    "Evet evet, /kickme tuşuna şimdiden bas.",
    "İşte, bu yüzüğü alın ve Mordor'a gidin.",
    "Efsaneye göre onlar hala çalışıyor...",
    "Harry Potter'ın aksine, ebeveynlerin seni benden koruyamaz.",
    "Korku öfkeye, öfke nefrete, nefret acıya yol açar. Korku içinde kaçmaya devam edersen,"
    "bir sonraki Vader sen olabilirsin.",
    "Birden fazla hesaplama yapıldıktan sonra, dalaverelerine olan ilgimin tam olarak 0 olduğuna karar verdim.",
    "Efsaneye göre onlar hala çalışıyor.",
    "Devam et, seni burda istediğimize emin değilim.",
    "Sen bir sihirb- Oh. Bekle. Sen Harry değilsin, devam et.",
    "KORİDORDA KOŞMAYIN!",
    "Görüşürüz bebeğim.",
    "Kim köpekleri saldı?",
    "Komik çünkü kimse takmıyor.",
    "Ah, ne büyük kayıp. Bu seferkini sevmiştim.",
    "Açıkcası canım, umrumda değil.",
    "Sütüm tüm erkekleri avluya çekiyor... Daha hızlı koş!",
    "Gerçeği KALDIRAMAZSIN!",
    "Uzun zaman önce, çok çok uzaktaki bir galakside birileri takabilirdi. Ama artık değil.",
    "Hey, onlara bak! Kaçınılmaz banhammer'dan kaçıyorlar... Ne kadarda tatlı.",
    "Han önce vuruldu. Ben de öyle yapacağım",
    "Beyaz tavşanın, arkasında ne yapıyorsun?",
    "Doktorunda söyleyeceği gibi... KAÇ!",
]


HELLOSTR = [
    "`Merhaba !`",
    "`‘Ello, gov'nor!`",
    "`Ne oluyor’?`",
    "`‘Naber, ev dilimi?`",
    "`Selam, selam, selam!`",
    "`Merhaba, kim var, ben konuşuyorum.`",
    "`Bunun kim olduğunu biliyorsun.`",
    "`Yo!`",
    "`Naber.`",
    "`Selam ve selamlama!`",
    "`Merhaba güneş!`",
    "`Selam, merhaba!`",
    "`Ne tekme atıyorsun küçük tavuk?`",
    "`Peek-a-boo!`",
    "`Howdy-doody!`",
    "`Hey there, freshman!`",
    "`I come in peace!`",
    "`Ahoy, matey!`",
    "`Hiya!`",
    "`Oh retarded gey! Well Hello`",
]

SHGS = [
    "┐(´д｀)┌",
    "┐(´～｀)┌",
    "┐(´ー｀)┌",
    "┐(￣ヘ￣)┌",
    "╮(╯∀╰)╭",
    "╮(╯_╰)╭",
    "┐(´д`)┌",
    "┐(´∀｀)┌",
    "ʅ(́◡◝)ʃ",
    "ლ(ﾟдﾟლ)",
    "┐(ﾟ～ﾟ)┌",
    "┐('д')┌",
    "ლ｜＾Д＾ლ｜",
    "ლ（╹ε╹ლ）",
    "ლ(ಠ益ಠ)ლ",
    "┐(‘～`;)┌",
    "ヘ(´－｀;)ヘ",
    "┐( -“-)┌",
    "乁༼☯‿☯✿༽ㄏ",
    "ʅ（´◔౪◔）ʃ",
    "ლ(•ω •ლ)",
    "ヽ(゜～゜o)ノ",
    "ヽ(~～~ )ノ",
    "┐(~ー~;)┌",
    "┐(-。ー;)┌",
    r"¯\_(ツ)_/¯",
    r"¯\_(⊙_ʖ⊙)_/¯",
    "乁ʕ •̀ ۝ •́ ʔㄏ",
    r"¯\_༼ ಥ ‿ ಥ ༽_/¯",
    "乁( ⁰͡  Ĺ̯ ⁰͡ ) ㄏ",
]

CRI = [
    "أ‿أ",
    "╥﹏╥",
    "(;﹏;)",
    "(ToT)",
    "(┳Д┳)",
    "(ಥ﹏ಥ)",
    "（；へ：）",
    "(T＿T)",
    "（πーπ）",
    "(Ｔ▽Ｔ)",
    "(⋟﹏⋞)",
    "（ｉДｉ）",
    "(´Д⊂ヽ",
    "(;Д;)",
    "（>﹏<）",
    "(TдT)",
    "(つ﹏⊂)",
    "༼☯﹏☯༽",
    "(ノ﹏ヽ)",
    "(ノAヽ)",
    "(╥_╥)",
    "(T⌓T)",
    "(༎ຶ⌑༎ຶ)",
    "(☍﹏⁰)｡",
    "(ಥ_ʖಥ)",
    "(つд⊂)",
    "(≖͞_≖̥)",
    "(இ﹏இ`｡)",
    "༼ಢ_ಢ༽",
    "༼ ༎ຶ ෴ ༎ຶ༽",
]

SLAP_TEMPLATES = [
    "{user1} {hits} {victim} with a {item}.",
    "{user1} {hits} {victim} in the face with a {item}.",
    "{user1} {hits} {victim} around a bit with a {item}.",
    "{user1} {throws} a {item} at {victim}.",
    "{user1} grabs a {item} and {throws} it at {victim}'s face.",
    "{user1} {hits} a {item} at {victim}.",
    "{throws} a few {item} at {victim}.",
    "{user1} grabs a {item} and {throws} it in {victim}'s face.",
    "{user1} launches a {item} in {victim}'s general direction.",
    "{user1} sits on {victim}'s face while slamming a {item} {where}.",
    "{user1} starts slapping {victim} silly with a {item}.",
    "{user1} pins {victim} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {victim} with it.",
    "{user1} starts slapping {victim} silly with a {item}.",
    "{user1} holds {victim} down and repeatedly {hits} them with a {item}.",
    "{user1} prods {victim} with a {item}.",
    "{user1} picks up a {item} and {hits} {victim} with it.",
    "{user1} ties {victim} to a chair and {throws} a {item} at them.",
    "{user1} {hits} {victim} {where} with a {item}.",
    "{user1} ties {victim} to a pole and whips them {where} with a {item}."
    "{user1} gave a friendly push to help {victim} learn to swim in lava.",
    "{user1} sent {victim} to /dev/null.",
    "sent {victim} down the memory hole.",
    "{user1} beheaded {victim}.",
    "threw {victim} off a building.",
    "{user1} replaced all of {victim}'s music with Nickelback.",
    "{user1} spammed {victim}'s email.",
    "made {victim} a knuckle sandwich.",
    "{user1} slapped {victim} with pure nothing.",
    "{user1} hit {victim} with a small, interstellar spaceship.",
    "{user1} quickscoped {victim}.",
    "put {victim} in check-mate.",
    "{user1} RSA-encrypted {victim} and deleted the private key.",
    "{user1} put {victim} in the friendzone.",
    "{user1} slaps {victim} with a DMCA takedown request!"]


ITEMS = [
    "demir tencere",
    "büyük alabalık",
    "beyzbol sopası",
    "kriket sopası",
    "tahta baston",
    "çivi",
    "yazıcı",
    "kürek",
    "tüplü monitör",
    "fizik defteri",
    "tost makinası",
    "Richard Stallman'ın portresi",
    "televizyon",
    "beş ton kamyon",
    "koli bandı",
    "kitap",
    "dizüstü bilgisayar",
    "eski televizyon",
    "kayalı çuval",
    "gökkuşağı alabalığı",
    "plastik tavuk",
    "çivili sopa",
    "yangın söndürücü",
    "ağır taş",
    "kir yığını",
    "arı kovanı",
    "çürük et parçası",
    "ayı",
    "tonlarca tuğla",
]

THROW = [
    "atıyor",
    "fırlatıyor",
    "savuruyor",
    "yağdırıyor",
]

HIT = [
    "vuruyor",
    "sert vuruyor",
    "tokatlıyor",
    "yumrukluyor",
    "geçiriyor",
]

WHERE = ["in the chest", "kafanın üstünde", "popo üzerinde", "kasıkta"]
